### ISSUE TITLE
Output only exported funcs

### ISSUE THREAD

**Issue by sinhrks** [yutannihilation/allYourFigureAreBelongToUs#3]
Is it possible to skip functions not defined in `NAMESPACE`?

**Comment by yutannihilation** [comment]
Thanks for reporting!

Now Rds not related to exported objects are filtered out. 

https://github.com/yutannihilation/allYourFigureAreBelongToUs/commit/f3672042a531a1008d6365fcc23260ae74fe6e08

Does this make sense for you?

**Comment by sinhrks** [comment]
Thanks. Looks gr8 for me:)

**Comment by yutannihilation** [comment]
![happy](http://i.giphy.com/flo7vS2shAZl6.gif)
